# Generated by Django 4.0.1 on 2022-01-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_article_comments_comments_artitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='artitle',
        ),
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='blog.article'),
        ),
    ]
