# Generated by Django 4.0.1 on 2022-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
    ]
